### ISSUE TITLE
fenchJSON must use external network

### ISSUE THREAD

**Issue by Davont** [code-hike/lighter#14]
I looked at the source code and found that the selection and configuration of the language must be from the `https://lighter.codehike.org/api/ `api, but due to the work environment, we cannot access this website, resulting in failure to start code-hike

**Comment by pomber** [comment]
It first tries to use the file system, if for some reason fails to load the grammars from the file system (for example in edge functions) it uses the network.

**Comment by Davont** [comment]
Thanks for your reply. Is there a corresponding interface in `codehike` that provides the file entry path? I've looked at the config parameters and I only see a `filePath` parameter, but I'm not sure.

**Comment by pomber** [comment]
For loading the grammars? there's no filePath, it looks for the node_modules folder in a couple of places. If it's not working for you tell me more about your particular case.
