### ISSUE TITLE
Possible to see if a language is available?

### ISSUE THREAD

**Issue by imownbey** [code-hike/lighter#18]
This library looks really great and I am hoping to start using it. One thing I need to do, though, is see if a language is available (right now we are just parsing the extension by `split(".").last()` and trying to use that for lang). That will cause `Unknown language` errors though for filenames like "env.development" though.

Is it possible to check to see if a language is available in a relatively fast way so I can just default to "text" if not?

**Comment by pomber** [comment]
Yes. There's `LANG_NAMES`:

```js
import { LANG_NAMES } from "@code-hike/bright"
```

**Comment by imownbey** [comment]
Amazing thank you!
