### ISSUE TITLE
Edge support?

### ISSUE THREAD

**Issue by imownbey** [code-hike/lighter#19]
I think right now this wont support edge based on how it is loading the WASM (and due to dependence on FS although maybe the browser version can be used?). I wondered if somehow using https://vercel.com/docs/concepts/functions/edge-functions/wasm this could be shipped to an edge function, though.

**Comment by pomber** [comment]
I think I tried it and it works, but I may be wrong. It doesn't use fs if it's not available.

**Comment by imownbey** [comment]
Oh great okay will try!

**Comment by pomber** [comment]
> Oh great okay will try!

let me know how it goes

**Comment by imownbey** [comment]
mmm it did not work (at least on vercel) but I dont remember why. Will update this thread when I retry it.

**Comment by MaxLeiter** [comment]
It doesn't seem to be working for me due to the `https` module:

```
- error ./node_modules/.pnpm/@code-hike+lighter@0.6.6/node_modules/@code-hike/lighter/dist/browser.esm.mjs:16:24
Module not found: Can't resolve 'https'
```

**Comment by pomber** [comment]
Strange, it should only import 'https' if 'fetch' isn't available.

**Comment by tom-sherman** [comment]
In cloudflare workers (and I presume Vercel as well, as they use the cloudflare runtime under the hood) you need to setup a binding to a WASM binary and then reference it.

See https://developers.cloudflare.com/workers/platform/web-assembly/javascript/

So without some bundler magic to replace the WASM import in the lighter code, I don't think it'll work right now.

**Comment by pomber** [comment]
`v0.8.0` should fix this. At least for Vercel's edge. 

I had problems with old versions of Next.js (they were ignoring the `worker` conditional export in lighter's package json), so try updating next.js first if you have problems.

**Comment by fat** [comment]
I'm seeing this issue with our edge implementation

<img width="514" alt="image" src="https://github.com/code-hike/lighter/assets/169705/8eb5bc26-903f-4991-a743-b58d701b0c51">


Anything special we might have missed?

**Comment by fat** [comment]
(this is on vercel / nextjs app dir)
