### ISSUE TITLE
Escape annotations

### ISSUE THREAD

**Issue by pomber** [code-hike/lighter#26]
There should be a way to escape comment annotations. 

See https://github.com/code-hike/codehike/issues/367 for an unexpected annotation with no way to escape.

Also, for Code Hike docs, I want to show the comments without converting them to annotations:
![image](https://github.com/code-hike/lighter/assets/1911623/661b321a-1c2c-4021-b9df-2b898f23c843)

**Comment by ldemo** [comment]
If add something about excape rule into the comment which we want to keep. 
There may be confusion about the result.
Like this.👇

```jsx
// before
const obj = {
  // keep:label: 1
}

// after
const obj = {
  // label: 1
}

```

I prefer this.👇

```jsx
// before
const obj = {
  // annotation-disabled-nextline
  // label: 1
}

// after
const obj = {
  // label: 1
}

```

**Comment by pomber** [comment]
My current idea is to add a setting to Code Hike to include a prefix in annotations:

````mdx

<CH.Code annotationPrefix="ch-">

```js
// label this isn't an annotation
// ch-label this is an annotation
console.log(1)
```

</CH.Code>

````

**Comment by mklemersson** [comment]
@pomber not a bad idea although this would make any user tied to use for every line of comment the specified prefix, right?

**Comment by pomber** [comment]
> @pomber not a bad idea although this would make any user tied to use for every line of comment the specified prefix, right?

Yes, but only for that codeblock.

It could also be used as a global setting. Something like:

```js
{ annotationPrefix: "@" }
```

And then you use it anywhere like:

````mdx

```js
// @label annotation
// label not an annotation
console.log(1)
```

````
