### ISSUE TITLE
Support Gatsby Partial Hydration

### ISSUE THREAD

**Issue by tom-sherman** [code-hike/lighter#32]
When I try to use this project inside of Gatsby with partial hydration it doesn't work.

```
../node_modules/.pnpm/@code-hike+lighter@0.6.6/node_modules/@code-hike/lighter/dist/browser.esm.mjs
Module not found: Can't resolve 'https' in '/Users/tom.sherman/code/perfect-syntax/node_modules/.pnpm/@code-hike+lighter@0.6.6/node_modules/@code-hike/lighter/dist'
```

I'm raising it here because it's weird to me that the `browser` entry contains a reference to a node module, feels like a bug with lighter and not gatsby

**Comment by tom-sherman** [comment]
It's absolutely possible I just don't understand gatsby partial hydration haha, maybe server components in this environment aren't meant to perform fetches and you're instead supposed to use gatsby's graphql stuff 🤔

**Comment by pomber** [comment]
Try a newer version of Lighter, I fixed that a couple of versions ago. (sometimes webpack ignore the "dynamic" part in dynamic imports)

**Comment by tom-sherman** [comment]
Ok yep that seems to work. Not fully working with my use case but I think this is because Gatsby doesn't support async server components right now.

@pomber btw, have you gotten bright to work with Gatsby partial hydration?

**Comment by pomber** [comment]
> @pomber btw, have you gotten bright to work with Gatsby partial hydration?

haven't tried, only tried next.js and waku
