### ISSUE TITLE
Add TalonScript definition 

### ISSUE THREAD

**Issue by Nova38** [code-hike/lighter#44]
Would it be possible to include the grammer for talonscript? Here is a link to the repo that is used for the vscode highlighting extension. It has the tmLanguage file located here (https://github.com/mrob95/vscode-TalonScript/blob/d422be3703e2b726c3538015bff9015a642eeb3e/syntaxes/talon.tmLanguage.yml). I would like to use code-hike in a docusaurus website and be able to have the files syntax highlighted. Currently, it is not easy to use Shiki with docusaurus and code-hike looks like a good alternative. (https://github.com/code-hike/examples/tree/main/with-docusaurus) Rewriting the grammar to be usable with the prismjs is proving challenging, so being able to just reuse the existing language definition would be nice.

- Repo (https://github.com/mrob95/vscode-TalonScript/tree/master)

The language name for use in markdown code snippets should be `talon` 

It was previously included in github syntax highlighter.  https://github.com/github-linguist/linguist/pull/5810

Some background on the Language:
- https://talon.wiki/
- https://talonvoice.com/

**Comment by pomber** [comment]
Hi, we now get the grammars from https://github.com/shikijs/textmate-grammars-themes, you'll find instructions to add a grammar there.

**Comment by Nova38** [comment]
Thanks for that link! I got my pull request merged upstream

**Comment by Nova38** [comment]
Does it auto update when a new release upstream is published or does it manually have to be updated to the latest version of the textmate grammars?

**Comment by pomber** [comment]
> Does it auto update when a new release upstream is published or does it manually have to be updated to the latest version of the textmate grammars?

sorry for the delay, should be updated now
