### ISSUE TITLE
Update to use tm-grammars@1.22.0 please

### ISSUE THREAD

**Issue by vkarpov15** [code-hike/lighter#47]
tm-grammars@1.22.0 was just released with Polar support re: #40. Can you please update this package to pull the latest grammars from tm-grammars?

In general, would be great if lighter pulled grammars automatically from tm-grammars rather than needing a new release every time tm-grammars ships a new release.

**Comment by pomber** [comment]
Hi, do you want to send a PR? you can follow the steps here https://github.com/code-hike/lighter/blob/main/known-issues.md#new-grammars

**Comment by vkarpov15** [comment]
Done in #48

**Comment by pomber** [comment]
thanks!
